import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Watch(props) {
  const { nodes, materials } = useGLTF('/apple_watch_ultra_2.glb')
  return (
    <group scale={[35,35,35]} {...props} dispose={null}>
      <group scale={0.01}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.NONHYSHLUQzoyez.geometry}
          material={materials.JSFaTttTQosHtdR}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.nUikKFsvZdptvXF.geometry}
          material={materials.edhWAPEBZsqCLTg}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.VHnHbLOyhEXLvWA.geometry}
          material={materials.edYkGGAdRWeopLP}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.DCiPNWQGULbWNNE.geometry}
          material={materials.AGtKlWnOInmqNQI}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.LbodUHJUCGqowCz.geometry}
          material={materials.PmrTDgoSkxCPUel}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.BMKlRAQYzgiNCrq_1.geometry}
          material={materials.yKAKXxwHUkGVYpC}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.joGEgikMuDmcVlT.geometry}
          material={materials.GXPSJdzybTrBefY}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.ytGVVkppetlPrjk.geometry}
          material={materials.CdZJpyOXLDMygZg}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.bXoKVYbQhcORrRo.geometry}
          material={materials.AGtKlWnOInmqNQI}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.LMTUXYhSYYJrnsy_0.geometry}
          material={materials.LMTUXYhSYYJrnsy_0}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.HoKUOQkmlXGGrun.geometry}
          material={materials.YtajTVWccmKRZBL}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.LMTUXYhSYYJrnsy.geometry}
          material={materials.edhWAPEBZsqCLTg}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.niuesVpLyOylhzG.geometry}
          material={materials.edhWAPEBZsqCLTg}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.dAobUVRiwHRHUwW.geometry}
          material={materials.GvXrALMIeaGmIJo}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.odYscQETIRVJKxR.geometry}
          material={materials.KjETpDnldvdbNBw}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.qHpopFXBXmHOUYS.geometry}
          material={materials.VJcIxaYCeMHzzAJ}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.AXTiAWNANGWNPZh.geometry}
          material={materials.vqobCvtAVyNLbeh}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.pYoTjWyHwknCsXs.geometry}
          material={materials.edhWAPEBZsqCLTg}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.GYKIDhUtSmfksAh.geometry}
          material={materials.edhWAPEBZsqCLTg}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.tZSTMNOYIPNFEiO.geometry}
          material={materials.YtajTVWccmKRZBL}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.IIYcDhGuQelMSoT.geometry}
          material={materials.JlRKetQcktLwJwa}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.jGEqmDFMbHJGHIM.geometry}
          material={materials.NfRpqTxrWQxoAIy}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.EefvmwIVeXQqJgK.geometry}
          material={materials.gYvxxOpBYwEcvOZ}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.pPJyCszCvDGrLse.geometry}
          material={materials.edhWAPEBZsqCLTg}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.gkDXZCmXAkhmUzR.geometry}
          material={materials.gYvxxOpBYwEcvOZ}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.UNygooOJQBdvEQH.geometry}
          material={materials.ihcWbztBiuXfzKC}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.URfXVlSvtJbSCOD.geometry}
          material={materials.EbFYvXZFEOELnji}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.OFYufNMwvtHmxdH.geometry}
          material={materials.hSvQcziHKpXubDY}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.mcBIQkSNmBqhwzR.geometry}
          material={materials.CdZJpyOXLDMygZg}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.dEKwzvajmGpjRpl.geometry}
          material={materials.yXTwmSCvToGuMDP}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.iQrteZnlrWZpbxz.geometry}
          material={materials.VkUcBAhoopQFcky}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.ggBokQJJgYcckom.geometry}
          material={materials.IvaXKlaVZetAvuj}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.SWRxiioprGlZKOq.geometry}
          material={materials.dSEglLtoqwjlQIP}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.AnKriXdRdkHvVgp.geometry}
          material={materials.IsuszdatyklnjoT}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.nKBIvEakrYhfdsQ.geometry}
          material={materials.ICUREbcRKnCadKa}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.VqmyRLxQuilpALX.geometry}
          material={materials.CevCCqOWPSfMvyq}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.IYFwQnCDaiSiRdc.geometry}
          material={materials.AGtKlWnOInmqNQI}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.FiiGAhWFHdUxhDn.geometry}
          material={materials.boERCOkfaeYKPmb}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.pVqLnJdxODmWtTg.geometry}
          material={materials.troyYZUIqRYbiDX}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.vyDTdhAtbzsQFUf.geometry}
          material={materials.ivgxAOQoWknkmNj}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.fOvUJMAYMqVGOTV.geometry}
          material={materials.FsJfKVbzNLXJeBa}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.ffjHNJzYIjDziJe.geometry}
          material={materials.sTxeXXVKohXeDJU}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.dGxaGtgSeaFVukl.geometry}
          material={materials.sTxeXXVKohXeDJU}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.YXUXfLDEwbvOPVY.geometry}
          material={materials.sTxeXXVKohXeDJU}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.jLHIkNOojYqBogV.geometry}
          material={materials.sTxeXXVKohXeDJU}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.OmcQxRYSzLYYjzi.geometry}
          material={materials.sTxeXXVKohXeDJU}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.HGmbyGfKBcsbZXU.geometry}
          material={materials.sTxeXXVKohXeDJU}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.EZmdWXCjqrUDeoX.geometry}
          material={materials.lgIBGhMXHpTEcfq}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.KUPfCqZVKycFVaN.geometry}
          material={materials.lgIBGhMXHpTEcfq}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.PiDhoxwwGLYiaUX_0.geometry}
          material={materials.sTxeXXVKohXeDJU}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.RJSoCQhkGkkzpXt_0.geometry}
          material={materials.sTxeXXVKohXeDJU}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.YufihILXVHVrDwt.geometry}
          material={materials.lgIBGhMXHpTEcfq}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.kAITCUcjTiAaCrp.geometry}
          material={materials.lgIBGhMXHpTEcfq}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.wKIPMqpyTsCHWIy.geometry}
          material={materials.edhWAPEBZsqCLTg}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.AGCoudWoaDmiMRH.geometry}
          material={materials.edhWAPEBZsqCLTg}
        />
      </group>
    </group>
  )
}

useGLTF.preload('/apple_watch_ultra_2.glb')